auth_function_name = "auth"
auth_handler = "auth_lambda_function.handler"
auth_runtime = "python3.9"
auth_lambda_source = "auth-lambda.py"
auth_lambda_filename = "auth-lambda.zip"
bucket_arn = "123456789::lambda"
bucket_name = "lambda-bucket"
function_name = "my-function"
handler = "lambda_function.handler"
iam_role_name = "iam-role"
lambda_source = "lambda.py"
lambda_filename = "lambda.zip"
runtime = "python3.9"
security_groups = "my-security-group"
tags = { foo = "bar" }
vpc_subnet_0 = "subnet_0"
vpc_subnet_1 = "subnet_1"
